server:
  port: 9009
spring:
  application:
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.220.132
aliyun:
  sms:
    accessKeyId: #改成自己的AccessKeyID
    accessKeySecret: #改成自己的AccessKeySecret
    template_code: SMS_204985837
    sign_name: 黑马
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true