server:
  port: 12000
spring:
  application:
    name: tensquare-config #指定服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/tiancixiong/tensquare-config.git
  rabbitmq:
    host: 192.168.220.132
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh