server:
  port: 9006
spring:
  application:
    name: tensquare‐spit #指定服务名
  data:
    mongodb:
      host: 192.168.220.132 #MongoDB服务器主机地址
      database: spitdb #数据库名
  redis:
    host: 192.168.220.132 #Redis服务器主机地址