server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 1234
  jpa:
    database: MySQL
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8 #东八区
  redis:
    host: 192.168.220.132 #Redis节点
  rabbitmq:
    host: 192.168.220.132 #RabbitMQ节点
jwt:
  config:
    key: itcast
    ttl: 3600000 #1个小时
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
